# .streamlit/secrets.toml

[admin]
password = "Admin_FTD_Pass_2026" # 👈 Đặt mật khẩu đăng nhập Admin của bạn tại đây

[api]
app_url = "https://script.google.com/macros/s/AKfycbwp-rsl_AGNnnmsVC83T2Eqo_0SF8xmiyKIXv61rvPAkiCPnF2dnPVoAKdSau776h3O2Q/exec" # 👈 Dán cái link Web App URL bạn vừa copy ở Bước 1 vào đây
